package com.chinasofti.mapper;

import com.chinasofti.pojo.Faceuser;
import com.chinasofti.pojo.FaceuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaceuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    long countByExample(FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int deleteByExample(FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int insert(Faceuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int insertSelective(Faceuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    List<Faceuser> selectByExampleWithBLOBs(FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    List<Faceuser> selectByExample(FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    Faceuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Faceuser record, @Param("example") FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Faceuser record, @Param("example") FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByExample(@Param("record") Faceuser record, @Param("example") FaceuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByPrimaryKeySelective(Faceuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Faceuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faceuser
     *
     * @mbg.generated Mon Sep 30 22:46:52 CST 2019
     */
    int updateByPrimaryKey(Faceuser record);
}